# Generated by Django 3.1.1 on 2020-09-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parkname', models.CharField(max_length=10)),
                ('parkfacility', models.CharField(max_length=10)),
                ('parkid', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='employees',
        ),
    ]
