# Generated by Django 2.0.7 on 2020-09-10 13:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=100)),
                ('latitute', models.FloatField()),
                ('longitude', models.FloatField()),
                ('park_facility', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20)),
                ('park_equipment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), size=20)),
                ('park_score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
