# Generated by Django 2.0.7 on 2020-09-10 23:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='latitute',
        ),
        migrations.RemoveField(
            model_name='park',
            name='longitude',
        ),
        migrations.AddField(
            model_name='park',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
