# Generated by Django 2.0.7 on 2020-09-10 23:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapi', '0002_auto_20200910_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='park_equipment',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), null=True, size=20),
        ),
        migrations.AlterField(
            model_name='park',
            name='park_facility',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), null=True, size=20),
        ),
    ]
