# Generated by Django 2.0.7 on 2020-09-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkapi', '0003_auto_20200910_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='latitute',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='park',
            name='longitude',
            field=models.FloatField(default=12.12),
            preserve_default=False,
        ),
    ]
