# Generated by Django 2.0.7 on 2020-09-11 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkapi', '0004_auto_20200911_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park',
            name='latitute',
        ),
        migrations.RemoveField(
            model_name='park',
            name='longitude',
        ),
    ]
